
#ifndef _MOUSE_EVENT_H_
#define _MOUSE_EVENT_H_

// Generated by Java: EVENT_MOUSE_CLICKED 
#define EVENT_MOUSE_ENTERED  (1 << 1)
#define EVENT_MOUSE_EXITED   (1 << 2)
#define EVENT_MOUSE_PRESSED  (1 << 3)
#define EVENT_MOUSE_RELEASED (1 << 4)
#define EVENT_MOUSE_MOVED    (1 << 5)
// Generated by Java: EVENT_MOUSE_DRAGGED  (1 << 6)

#endif
