
#ifndef _MOUSE_EVENT_H_
#define _MOUSE_EVENT_H_

// Generated by Java: EVENT_MOUSE_CLICKED  = 200;
#define EVENT_MOUSE_ENTERED  201
#define EVENT_MOUSE_EXITED   202
#define EVENT_MOUSE_PRESSED  203
#define EVENT_MOUSE_RELEASED 204
#define EVENT_MOUSE_MOVED    205
// can't find how to regenerate this file, adding manually
#define EVENT_MOUSE_WHEEL_MOVED    207
// Generated by Java:  EVENT_MOUSE_DRAGGED  = 206;

#endif
