
#ifndef _WINDOW_EVENT_H_
#define _WINDOW_EVENT_H_

#define EVENT_WINDOW_RESIZED = 100;
#define EVENT_WINDOW_MOVED   = 101;
#define EVENT_WINDOW_DESTROY_NOTIFY = 102;
#define EVENT_WINDOW_GAINED_FOCUS = 103;
#define EVENT_WINDOW_LOST_FOCUS = 104;
#define EVENT_WINDOW_REPAINT = 105; // TODO

#endif
