/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.2-dev-2485-g691d019899"
#endif /* AVUTIL_FFVERSION_H */
