#!/bin/bash
SRC="./test/oldgears/src/"
LIBS="./test/oldgears/lib/jogl.jar:./test/oldgears/lib/jogl.all.jar:./test/oldgears/lib/jogl.awt.jar"
OUTPUT="./test/oldgears/build"

echo "Back to the Future"
mkdir $OUTPUT
./lib/jackpotc -sourcepath $SRC -cp $LIBS -d $OUTPUT -Ajackpot30_extra_hints=./jogl1Tojogl2.hint `find $SRC -type f -name "*.java"`
