#!/bin/bash
PROJECT="./test/oldgears"
SRC="$PROJECT/src"
GENSRC="$PROJECT/gensrc"
LIBS="$PROJECT/lib/old/jogl.jar:$PROJECT/lib/new/jogl.all.jar:$PROJECT/lib/new/jogl.awt.jar"
OUTPUT="$PROJECT/build"
FILESET=`find $SRC -type f -name "*.java"`

echo "Back to the Future"
echo "transforming files: $FILESET"
mkdir $OUTPUT
./lib/jackpotc -sourcepath $SRC -cp $LIBS -d $OUTPUT -Ajackpot30_extra_hints=./jogl1Tojogl2.hint $FILESET

echo "patching..."
mkdir "$GENSRC"
mkdir "$GENSRC/jogl2/"
mkdir "$GENSRC/jogl2/gears/"
patch -o $GENSRC/jogl2/gears/Gears.java $FILESET ${OUTPUT}/META-INF/upgrade/upgrade.diff

echo "done"
